import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import { Toaster } from "sonner"; // 👈 si usas sonner para notificaciones
import { Header } from "../../components/Header";
import { Footer } from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const renderPage = () => {
    return children; // 👈 Next.js renderiza aquí la página actual
  };

  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="min-h-screen bg-white">
            <Header showSearch={true} />
            {renderPage()}
            <Footer />
            <Toaster position="top-center" richColors />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
